version: '3'

services:
  caddy:
    depends_on:
      - php
    image: caddy
    ports:
      - 443:443
    volumes:
      - ..:/srv/app
      - ../data:/srv/app/data
      - ./Caddyfile:/etc/caddy/Caddyfile

  php:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    env_file:
      - ./secrets.env
    image: php:fpm
    volumes:
      - ..:/srv/app
