version: '3'

services:
  caddy:
    depends_on:
      - php
    image: caddy
    ports:
      - 443:443
    volumes:
      - ..:/srv/app
      - ./Caddyfile:/etc/caddy/Caddyfile
  composer:
    image: composer:2
    volumes:
      - ..:/app
      - vendor:/app/vendor
    command: install --ignore-platform-reqs

  php:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    env_file:
      - ./secrets.env
    image: php:fpm
    volumes:
      - ../src:/srv/app/src
      - vendor:/srv/app/vendor
      - ../data:/srv/app/data

volumes:
  vendor:
