<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;

use function Lamb\Response\robots_txt_body;
use function Lamb\Response\robots_txt_content;
use function Lamb\Route\register_app_routes;

/**
 * robots.txt is generated by default: it allows crawling, points at the
 * sitemap, and disallows the private routes. A static robots.txt dropped in the
 * web root overrides the generated one so it stays customisable.
 */
class RobotsTest extends TestCase
{
    protected function setUp(): void
    {
        if (!defined('ROOT_URL')) {
            define('ROOT_URL', 'https://example.com');
        }
        // robots.txt is derived from the registered private routes, so register
        // the application's route table exactly as index.php does first.
        $GLOBALS['routes'] = [];
        $GLOBALS['private_routes'] = [];
        register_app_routes('home', null, null);
    }

    public function testAllowsCrawling(): void
    {
        $body = robots_txt_body();
        $this->assertStringContainsString('User-agent: *', $body);
        $this->assertStringContainsString('Allow: /', $body);
    }

    public function testAdvertisesSitemap(): void
    {
        $this->assertStringContainsString('Sitemap: ' . ROOT_URL . '/sitemap.xml', robots_txt_body());
    }

    public function testDisallowsAdminRoutes(): void
    {
        $body = robots_txt_body();
        $expected = [
            '/_cron', '/checkbox', '/delete', '/drafts', '/edit', '/login',
            '/logout', '/restore', '/scheduled', '/settings', '/trash', '/upload',
        ];
        foreach ($expected as $path) {
            $this->assertStringContainsString('Disallow: ' . $path, $body);
        }
    }

    public function testStaticFileOverridesGeneratedBody(): void
    {
        $dir = sys_get_temp_dir() . '/lamb-robots-' . uniqid();
        mkdir($dir);
        file_put_contents($dir . '/robots.txt', "User-agent: *\nDisallow: /\n");

        $this->assertSame("User-agent: *\nDisallow: /\n", robots_txt_content($dir));

        unlink($dir . '/robots.txt');
        rmdir($dir);
    }

    public function testGeneratedBodyUsedWhenNoStaticFile(): void
    {
        $dir = sys_get_temp_dir() . '/lamb-robots-' . uniqid();
        mkdir($dir);

        $this->assertSame(robots_txt_body(), robots_txt_content($dir));

        rmdir($dir);
    }
}
