name: CI

permissions:
  checks: write
  contents: read
  pull-requests: read

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main", "release" ]
  pull_request:

jobs:

  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Validate Composer
        run: composer validate

      - name: Security audit
        run: composer audit

      - name: Run PHPCS
        run: composer run lint

      - name: Run PHPStan
        run: composer run analyse

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2', '8.3', '8.4', '8.5' ]

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: ${{ matrix.php-version == '8.2' && 'pcov' || 'none' }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Codeception tests
        run: |
          php make-password.php $GITHUB_REF
          vendor/bin/codecept run --steps

      - name: Check code coverage
        if: matrix.php-version == '8.2'
        run: composer coverage

  ci:
    runs-on: ubuntu-latest
    needs: [quality, test]
    steps:
      - run: echo "All checks passed"
