name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ steps.composer-json.outputs.php-version }}

      - name: Get Composer PHP version
        id: composer-json
        run: |
          composer validate --no-check-publish
          echo "php-version=$(composer show -f json | jq -r '.require.php')" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Validate Composer
        run: composer validate

      - name: Run Codeception tests
        run: |
          php codecept run
