name: Composer Validate

permissions: read-all

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - production
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  composer-validate:
    name: Composer Validate
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ '8.1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Paths filters
        uses: dorny/paths-filter@v2
        id: paths
        with:
          filters: |
            workflows: &workflows
              - '.github/actions/**/*.yml'
              - '.github/workflows/**/*.yml'
            composer:
              - *workflows
              - 'composer.json'
              - 'composer.lock'

      - name: Setup
        if: ${{ steps.paths.outputs.composer == 'true' }}
        uses: ./.github/actions/setup-php
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Composer config
        if: ${{ steps.paths.outputs.composer == 'true' }}
        run: composer validate --no-check-all --no-check-publish
